
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/cmake-3.28.0-rc4-linux-x86_64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.4.0-1103-aws - x86_64
...
